version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/myapp/app
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/run_container
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/stop_container
      timeout: 300
      runas: root
